image: Ubuntu2004
branches:
  only:
    - master
skip_branch_with_pr: true

install: 
  - ps: Install-Module InvokeBuild -RequiredVersion 5.6.0 -Force
  - ps: Import-Module InvokeBuild

build_script:
  - ps: Invoke-Build UnitTest