name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ps

    - name: Run Unit Tests
      run: docker run -it -v $(pwd):/tmp/build ps invoke-build unittest

    - name: list
      run: pwd && ls -la